# Generated by Django 4.1.3 on 2022-11-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_nome', models.CharField(max_length=50)),
                ('salario', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora_consulta', models.DateTimeField()),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.pet')),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.veterinario')),
            ],
        ),
    ]
